{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase-postgres.fullname" . }}
  labels:
    {{- include "supabase-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ "supabase" | b64enc }}
{{- end }}
